apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unas-pro
provisioner: nfs.csi.k8s.io
parameters:
  server: unas-pro.prod.lionux.lan
  share: /var/nfs/shared/k8s/
reclaimPolicy: Retain
volumeBindingMode: Immediate
